---
# tasks file for docker_aws_instance
- name: Installing boto.
  pip:
    name: boto

- name: Launch instance
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    key_name: "{{ keypair }}"
    group_id: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    user_data: |
      #!/bin/bash
      yum install wget -y
      yum install epel-release -y
      yum install ansible -y
      wget -O- https://get.docker.com/ | sh
    wait: true
    wait_timeout: 500
    instance_tags:
      Name: Docker
      Environment: Production
    region: "{{ region }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 30
        delete_on_termination: true
    vpc_subnet_id: subnet-05078fa4222866fef
    assign_public_ip: true
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  loop: "{{ ec2.instances }}"
